{"name": "test_logosCheck", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_signupLogin.py:86: AssumptionFailure\n>>\tpytest.assume(str(appVersion) in \" 931 v12\")\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_signupLogin.py:86: AssumptionFailure\nE               >>\tpytest.assume(str(appVersion) in \" 931 v12\")\nE               AssertionError: assert False\n\nC:\\Program Files\\Python311\\Lib\\site-packages\\six.py:723: FailedAssumption"}, "attachments": [{"name": "stdout", "source": "47f4039d-2406-4b3b-8877-a1fd675e99fa-attachment.txt", "type": "text/plain"}], "start": 1746460534493, "stop": 1746460537521, "uuid": "8067dd11-0105-4206-8311-35c0f2770334", "historyId": "b835c8e5fcbbf0477f7f0fc0864c92af", "testCaseId": "b835c8e5fcbbf0477f7f0fc0864c92af", "fullName": "test_signupLogin#test_logosCheck", "labels": [{"name": "tag", "value": "starters"}, {"name": "suite", "value": "test_signupLogin"}, {"name": "host", "value": "Ayadi"}, {"name": "thread", "value": "24180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_signupLogin"}]}